disabled_rules:
  - trailing_whitespace
  - todo
  - type_name

opt_in_rules:
  - empty_count
  - force_cast
  - force_unwrapping
  - redundant_nil_coalescing

included:
  - airmeishi

excluded:
  - Pods
  - DerivedData
  - Carthage
  - airmeishiClip
  - airmeishiTests
  - airmeishiUITests
  - "**/Generated"
  - "**/*generated.swift"
  - "**/*.generated.swift"

line_length:
  warning: 160
  error: 240

file_length:
  warning: 900
  error: 1000

type_body_length:
  warning: 500
  error: 800

function_body_length:
  warning: 120
  error: 180

identifier_name:
  min_length:
    warning: 1
    error: 1
  allowed_symbols: ["_"]
  excluded:
    - id
    - URL

strict: false
reporter: "xcode"
