/**
 * Pear lane — RN-side wrapper around a `react-native-bare-kit` `Worklet`
 * running `pear/worklet/index.js` (bundled via `bare-pack`; see that
 * file's header + `scripts/pack-pear-worklet.mjs`). One `LaneHandle` is
 * one Bare thread; `joinTopic()` can be called any number of times on it
 * to open additional hyperswarm topics without spawning another worklet.
 *
 * Everything RN sends/receives from the worklet is a length-prefixed JSON
 * "envelope" frame over `Worklet.IPC` (see `frames.ts` for the wire
 * format, and `pear/worklet/index.js`'s header for the envelope
 * vocabulary: `_join`/`_leave`/`_send` out, `_ctrl`/`_frame` in). This
 * module owns demultiplexing those envelopes back to the right
 * `PearChannel` by topic.
 *
 * No challenge/response, card exchange, or presentation protocol lives
 * here — `PearChannel.send`/`onFrame` pass application frames through
 * completely opaque to this module. That protocol is A3.3 (real PoC) and
 * A5 (card/present wire protocol) work, entirely RN-side per the plan.
 */
import { Worklet } from 'react-native-bare-kit';
import { bytesToHex, sha256Bytes, err, ok, type Result } from '@solidarity/shared';

// Generated by `bun run pear:pack` (scripts/pack-pear-worklet.mjs) — typed
// via the `*.bundle.js` ambient module declaration in src/globals.d.ts.
import bundle from '../../pear/worklet/dist/index.bundle.js';

import { encodeFrame, FrameDecoder } from './frames';

/** `sha256("solidarity/pear/v1|" + did)` as lowercase hex — the hyperswarm
 *  topic two peers rendezvous on for a given DID. Both sides derive this
 *  independently from the same DID, so there's no separate "invite" step
 *  for the happy path (a peer that doesn't know the DID can't compute the
 *  topic and never discovers the swarm entry). */
export function pearTopicFor(did: string): string {
  return bytesToHex(sha256Bytes(`solidarity/pear/v1|${did}`));
}

export type PearJoinMode = 'server' | 'client' | 'both';

export type PearCtrlEvent =
  | { readonly topic: string; readonly ev: 'joined' }
  | { readonly topic: string; readonly ev: 'open'; readonly connId?: number }
  | { readonly topic: string; readonly ev: 'close'; readonly connId?: number }
  | { readonly topic: string; readonly ev: 'error'; readonly connId?: number; readonly message: string };

export interface PearChannel {
  /** Broadcast `frame` verbatim to every open connection on this topic.
   *  A no-op if nothing is connected yet (frame is dropped, not queued —
   *  callers that need queueing should hold off until an `onCtrl` 'open'
   *  fires). */
  send(frame: Record<string, unknown>): void;
  /** Subscribe to frames relayed from any peer on this topic. Returns an
   *  unsubscribe function. */
  onFrame(cb: (frame: Record<string, unknown>) => void): () => void;
  /** Subscribe to this topic's lifecycle events. Returns an unsubscribe
   *  function. */
  onCtrl(cb: (ev: PearCtrlEvent) => void): () => void;
  /** Leave the topic and drop this channel's listeners. Does not shut
   *  down the underlying lane/worklet — call `LaneHandle.shutdown()` for
   *  that. */
  close(): void;
}

export interface LaneHandle {
  joinTopic(topicHex: string, mode?: PearJoinMode): PearChannel;
  /** Terminates the worklet outright (no graceful per-topic drain — this
   *  is what `lifecycle.ts` calls on backgrounding, where the OS is about
   *  to kill the process's I/O anyway). */
  shutdown(): void;
}

export type LaneErrorCode = 'worklet_start_failed';

export interface LaneError {
  readonly code: LaneErrorCode;
  readonly message: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type -- reserved for future config (memoryLimit, etc.); kept as an explicit param so call sites don't need updating when it grows
export interface StartLaneOptions {}

export function startLane(_opts: StartLaneOptions = {}): Result<LaneHandle, LaneError> {
  let worklet: Worklet;
  try {
    worklet = new Worklet();
    worklet.start('/app.bundle', bundle);
  } catch (error) {
    return err({
      code: 'worklet_start_failed',
      message: error instanceof Error ? error.message : String(error),
    });
  }

  const decoder = new FrameDecoder();
  const frameListeners = new Map<string, Set<(frame: Record<string, unknown>) => void>>();
  const ctrlListeners = new Map<string, Set<(ev: PearCtrlEvent) => void>>();

  function routeEnvelope(value: Record<string, unknown>): void {
    const topic = typeof value['topic'] === 'string' ? value['topic'] : null;
    if (!topic) return;

    if (value['t'] === '_ctrl' && typeof value['ev'] === 'string') {
      const listeners = ctrlListeners.get(topic);
      if (!listeners || listeners.size === 0) return;
      const ctrlEvent = value as unknown as PearCtrlEvent;
      for (const cb of listeners) cb(ctrlEvent);
      return;
    }

    const frame = value['frame'];
    if (value['t'] === '_frame' && frame && typeof frame === 'object' && !Array.isArray(frame)) {
      const listeners = frameListeners.get(topic);
      if (!listeners || listeners.size === 0) return;
      for (const cb of listeners) cb(frame as Record<string, unknown>);
    }
  }

  const onIpcData = (chunk: Uint8Array): void => {
    const events = decoder.push(chunk);
    for (const event of events) {
      if (event.kind === 'error') continue; // malformed envelope from the worklet — nothing routable, drop
      routeEnvelope(event.value);
    }
  };
  worklet.IPC.on('data', onIpcData);

  function sendCommand(command: Record<string, unknown>): void {
    const encoded = encodeFrame(command);
    if (!encoded.ok) return; // command itself malformed (shouldn't happen — we build these) — nothing to send
    try {
      worklet.IPC.write(encoded.value);
    } catch {
      // Worklet already terminated — drop.
    }
  }

  function joinTopic(topicHex: string, mode: PearJoinMode = 'both'): PearChannel {
    if (!frameListeners.has(topicHex)) frameListeners.set(topicHex, new Set());
    if (!ctrlListeners.has(topicHex)) ctrlListeners.set(topicHex, new Set());
    sendCommand({ t: '_join', topic: topicHex, mode });

    return {
      send(frame) {
        sendCommand({ t: '_send', topic: topicHex, frame });
      },
      onFrame(cb) {
        const listeners = frameListeners.get(topicHex) ?? new Set();
        frameListeners.set(topicHex, listeners);
        listeners.add(cb);
        return () => { listeners.delete(cb); };
      },
      onCtrl(cb) {
        const listeners = ctrlListeners.get(topicHex) ?? new Set();
        ctrlListeners.set(topicHex, listeners);
        listeners.add(cb);
        return () => { listeners.delete(cb); };
      },
      close() {
        sendCommand({ t: '_leave', topic: topicHex });
        frameListeners.delete(topicHex);
        ctrlListeners.delete(topicHex);
      },
    };
  }

  function shutdown(): void {
    try {
      worklet.IPC.off('data', onIpcData);
    } catch {
      // Already torn down.
    }
    try {
      worklet.terminate();
    } catch {
      // Already dead.
    }
    frameListeners.clear();
    ctrlListeners.clear();
  }

  return ok({ joinTopic, shutdown });
}
