#!/usr/bin/env bash
# Persistent home for the Xcode Cloud post-clone hook. The runtime copy
# at apps/expo/ios/ci_scripts/ci_post_clone.sh is regenerated by the local
# `withXcodeCloudScripts` config plugin during `expo prebuild` because the
# whole ios/ directory is gitignored (and `expo prebuild --clean` wipes it).
#
# Edit THIS file; the plugin will sync it into the runtime location on
# the next prebuild.
set -euo pipefail

echo "▸ Solidarity Xcode Cloud post-clone"
echo "▸ cwd: $(pwd)"
echo "▸ CI_PRIMARY_REPOSITORY_PATH: ${CI_PRIMARY_REPOSITORY_PATH:-unset}"

REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(pwd)/../../../.." && pwd)}"
APP_DIR="$REPO_ROOT/apps/expo"

echo "▸ At repo root: $REPO_ROOT"
echo "▸ Preparing Expo iOS workspace for Xcode Cloud"

AIRMEISHI_BUN_INSTALL_ARGS="--frozen-lockfile" \
AIRMEISHI_EXPO_APP_DIR="$APP_DIR" \
AIRMEISHI_INSTALL_TOOLING=1 \
AIRMEISHI_IOS_PREBUILD_CLEAN=1 \
AIRMEISHI_REPO_ROOT="$REPO_ROOT" \
AIRMEISHI_SETUP_IOS_NATIVE_BINDINGS="${AIRMEISHI_SETUP_IOS_NATIVE_BINDINGS:-1}" \
"$APP_DIR/scripts/prepare-ios-workspace.sh"

echo "✓ Ready — Xcode Cloud will now archive + sign + ship to TestFlight."
