#!/bin/sh
# Persistent home for the Xcode Cloud post-clone hook. The runtime copy
# at apps/expo/ios/ci_scripts/ci_post_clone.sh is regenerated by the local
# `withXcodeCloudScripts` config plugin during `expo prebuild` because the
# whole ios/ directory is gitignored (and `expo prebuild --clean` wipes it).
#
# Edit THIS file; the plugin will sync it into the runtime location on
# the next prebuild.
set -euo pipefail

echo "▸ Solidarity Xcode Cloud post-clone"
echo "▸ cwd: $(pwd)"
echo "▸ CI_PRIMARY_REPOSITORY_PATH: ${CI_PRIMARY_REPOSITORY_PATH:-unset}"

cd "${CI_PRIMARY_REPOSITORY_PATH:-$(pwd)/../../../..}"
echo "▸ At repo root: $(pwd)"

echo "▸ Installing Node via Homebrew…"
brew install node

echo "▸ Installing Bun…"
brew install oven-sh/bun/bun

echo "▸ bun install (workspace root)…"
bun install --frozen-lockfile

echo "▸ expo prebuild --clean --platform ios…"
cd apps/expo
bunx expo prebuild --clean --platform ios --no-install

echo "✓ Ready — Xcode Cloud will now archive + sign + ship to TestFlight."
