/*
 * HybridNfcPassport.kt
 * @solidarity/nitro-nfc-passport (Android)
 *
 * Wraps jmrtd (http://jmrtd.org) for ICAO 9303 BAC/PACE/passive auth.
 * Mirrors the iOS counterpart's contract from src/specs/NfcPassport.nitro.ts.
 *
 * Required Gradle deps (added by autolinker):
 *   implementation("org.jmrtd:jmrtd:0.7.41")
 *   implementation("net.sf.scuba:scuba-sc-android:0.0.27")
 *
 * Codegen base class `HybridNfcPassportSpec` is generated by `bunx nitrogen`.
 */
package gg.solidarity.nitro.nfcpassport

import android.app.Activity
import android.content.Context
import android.nfc.NfcAdapter
import android.nfc.Tag
import android.nfc.tech.IsoDep
import com.margelo.nitro.nfcpassport.DataGroupsBundle
import com.margelo.nitro.nfcpassport.HybridNfcPassportSpec
import com.margelo.nitro.nfcpassport.NfcPassportMrz
import com.margelo.nitro.nfcpassport.PassportMRZ
import com.margelo.nitro.nfcpassport.PassportReadResult
import kotlinx.coroutines.CompletableDeferred
import net.sf.scuba.smartcards.CardService
import org.jmrtd.BACKey
import org.jmrtd.PassportService
import org.jmrtd.lds.icao.DG1File
import org.jmrtd.lds.SODFile

class HybridNfcPassport(private val context: Context) : HybridNfcPassportSpec() {

  @Volatile private var inFlight: CompletableDeferred<PassportReadResult>? = null

  override fun isAvailable(): Boolean {
    val adapter = NfcAdapter.getDefaultAdapter(context) ?: return false
    return adapter.isEnabled
  }

  override fun cancel() {
    inFlight?.completeExceptionally(CancellationException("user cancelled"))
    inFlight = null
  }

  override suspend fun read(mrz: PassportMRZ): PassportReadResult {
    val deferred = CompletableDeferred<PassportReadResult>()
    inFlight = deferred

    val activity = context as? Activity
      ?: throw IllegalStateException("Android NFC passport read requires an Activity context")

    NfcAdapter.getDefaultAdapter(activity)?.enableReaderMode(
      activity,
      { tag -> readPassport(tag, mrz, deferred) },
      NfcAdapter.FLAG_READER_NFC_A or NfcAdapter.FLAG_READER_SKIP_NDEF_CHECK,
      null
    )
    return deferred.await()
  }

  private fun readPassport(tag: Tag, mrz: PassportMRZ, out: CompletableDeferred<PassportReadResult>) {
    try {
      val isoDep = IsoDep.get(tag) ?: error("ISO-Dep not supported")
      isoDep.timeout = 10_000
      val ps = PassportService(
        CardService.getInstance(isoDep),
        PassportService.NORMAL_MAX_TRANCEIVE_LENGTH,
        PassportService.DEFAULT_MAX_BLOCKSIZE,
        true,
        false
      )
      ps.open()
      ps.sendSelectApplet(false)
      ps.doBAC(BACKey(mrz.documentNumber, mrz.dateOfBirth, mrz.dateOfExpiry))

      val dg1Bytes = ps.getInputStream(PassportService.EF_DG1).readBytes()
      val dg2Bytes = ps.getInputStream(PassportService.EF_DG2).readBytes()
      val sodBytes = ps.getInputStream(PassportService.EF_SOD).readBytes()
      val dg1 = DG1File(dg1Bytes.inputStream()).mrzInfo
      val sod = SODFile(sodBytes.inputStream())

      val passiveAuth = runCatching {
        sod.docSigningCertificate != null
      }.getOrDefault(false)

      out.complete(
        PassportReadResult(
          mrz = NfcPassportMrz(
            nationality = dg1.nationality,
            documentNumber = dg1.documentNumber,
            name = "${dg1.secondaryIdentifier} ${dg1.primaryIdentifier}".trim(),
            dateOfBirth = dg1.dateOfBirth,
            dateOfExpiry = dg1.dateOfExpiry,
            gender = dg1.gender.toString()
          ),
          dataGroups = DataGroupsBundle(
            dg1 = dg1Bytes,
            dg2 = dg2Bytes,
            dg14 = null,
            dg15 = null,
            sod = sodBytes
          ),
          chipUid = tag.id.joinToString("") { "%02x".format(it) },
          passiveAuthValid = passiveAuth
        )
      )
    } catch (e: Throwable) {
      out.completeExceptionally(e)
    } finally {
      inFlight = null
    }
  }
}

private class CancellationException(message: String) : RuntimeException(message)
