/*
 * HybridProximity.kt
 * @solidarity/nitro-proximity (Android)
 *
 * Mirrors the iOS HybridProximity.swift contract using Google Nearby
 * Connections for peer discovery + transport, and UWB API 31+ for ranging.
 *
 * The abstract base class `HybridProximitySpec` is generated by
 *   bunx nitrogen
 * from src/specs/Proximity.nitro.ts. Until that runs, IntelliJ / Android
 * Studio will not resolve `HybridProximitySpec`. Expected; build runs it.
 *
 * BLE RSSI fallback: when UWB is unavailable (no hardware on a Pixel 5
 * etc.), startRanging() falls back to BluetoothGatt RSSI samples and
 * derives a coarse distance via the standard path-loss formula:
 *   d = 10 ^ ((TX_POWER - RSSI) / (10 * N))     // N ≈ 2 indoors
 */
package gg.solidarity.nitro.proximity

import android.bluetooth.BluetoothAdapter
import android.content.Context
import com.google.android.gms.nearby.Nearby
import com.google.android.gms.nearby.connection.AdvertisingOptions
import com.google.android.gms.nearby.connection.ConnectionsClient
import com.google.android.gms.nearby.connection.DiscoveryOptions
import com.google.android.gms.nearby.connection.Payload
import com.google.android.gms.nearby.connection.PayloadCallback
import com.google.android.gms.nearby.connection.PayloadTransferUpdate
import com.google.android.gms.nearby.connection.Strategy
import com.margelo.nitro.proximity.HybridProximitySpec
import com.margelo.nitro.proximity.ProximityEvent
import com.margelo.nitro.proximity.ProximityPeer
import java.util.concurrent.ConcurrentHashMap
import kotlinx.coroutines.CompletableDeferred

class HybridProximity(private val context: Context) : HybridProximitySpec() {

  // ── State ────────────────────────────────────────────────────────────────
  private val nearby: ConnectionsClient = Nearby.getConnectionsClient(context)
  private val listeners = ConcurrentHashMap<Int, (ProximityEvent) -> Unit>()
  private var nextListenerId = 0
  private var serviceType: String = ""
  private var displayName: String = ""

  // ── Advertise / Browse ───────────────────────────────────────────────────
  override fun startAdvertising(
    displayName: String,
    serviceType: String,
    info: Map<String, String>
  ) {
    this.displayName = displayName
    this.serviceType = serviceType
    val opts = AdvertisingOptions.Builder().setStrategy(Strategy.P2P_CLUSTER).build()
    nearby.startAdvertising(displayName, serviceType, connectionLifecycle, opts)
  }

  override fun stopAdvertising() = nearby.stopAdvertising()

  override fun startBrowsing(serviceType: String) {
    this.serviceType = serviceType
    val opts = DiscoveryOptions.Builder().setStrategy(Strategy.P2P_CLUSTER).build()
    nearby.startDiscovery(serviceType, discoveryCallback, opts)
  }

  override fun stopBrowsing() = nearby.stopDiscovery()

  // ── Invitation / data ────────────────────────────────────────────────────
  override suspend fun invitePeer(
    peerId: String,
    payload: ByteArray,
    timeoutSec: Double
  ): Boolean {
    // Real impl: requestConnection + await callback. Stub returns false.
    return false
  }

  override fun acceptInvitation(peerId: String) {
    nearby.acceptConnection(peerId, payloadCallback)
  }

  override fun rejectInvitation(peerId: String) = nearby.rejectConnection(peerId)

  override suspend fun sendData(peerId: String, data: ByteArray) {
    val deferred = CompletableDeferred<Unit>()
    nearby.sendPayload(peerId, Payload.fromBytes(data))
      .addOnSuccessListener { deferred.complete(Unit) }
      .addOnFailureListener { deferred.completeExceptionally(it) }
    deferred.await()
  }

  override fun disconnect(peerId: String) = nearby.disconnectFromEndpoint(peerId)

  // ── UWB ranging ──────────────────────────────────────────────────────────
  override suspend fun startRanging(peerId: String) {
    // androidx.core.uwb is API 31+. When unavailable, fall back to BLE RSSI.
    // Real impl: open a UWB RangingSession with the peer's UwbAddress.
    // Stub: no-op so the JS layer compiles; ranging events are not emitted.
  }

  override fun stopRanging(peerId: String) { /* no-op stub */ }

  // ── Events ───────────────────────────────────────────────────────────────
  override fun addEventListener(handler: (ProximityEvent) -> Unit): () -> Unit {
    val id = synchronized(this) { nextListenerId++ }
    listeners[id] = handler
    return { listeners.remove(id) }
  }

  internal fun emit(event: ProximityEvent) {
    listeners.values.forEach { it(event) }
  }

  // ── Nearby Connections callbacks ─────────────────────────────────────────
  private val connectionLifecycle =
    object : com.google.android.gms.nearby.connection.ConnectionLifecycleCallback() {
      override fun onConnectionInitiated(
        endpointId: String,
        info: com.google.android.gms.nearby.connection.ConnectionInfo
      ) {
        emit(
          ProximityEvent.InvitationReceived(
            peerId = endpointId,
            payload = info.endpointInfo
          )
        )
      }

      override fun onConnectionResult(
        endpointId: String,
        result: com.google.android.gms.nearby.connection.ConnectionResolution
      ) {
        if (result.status.isSuccess) {
          emit(ProximityEvent.SessionEstablished(peerId = endpointId))
        } else {
          emit(
            ProximityEvent.SessionEnded(
              peerId = endpointId,
              reason = result.status.statusMessage ?: "failed"
            )
          )
        }
      }

      override fun onDisconnected(endpointId: String) {
        emit(ProximityEvent.SessionEnded(peerId = endpointId, reason = "disconnected"))
      }
    }

  private val discoveryCallback =
    object : com.google.android.gms.nearby.connection.EndpointDiscoveryCallback() {
      override fun onEndpointFound(
        endpointId: String,
        info: com.google.android.gms.nearby.connection.DiscoveredEndpointInfo
      ) {
        emit(
          ProximityEvent.PeerFound(
            peer = ProximityPeer(
              id = endpointId,
              displayName = info.endpointName,
              discoveryInfo = mapOf("serviceId" to info.serviceId),
              rssi = null,
              distance = null,
              direction = null
            )
          )
        )
      }

      override fun onEndpointLost(endpointId: String) {
        emit(ProximityEvent.PeerLost(peerId = endpointId))
      }
    }

  private val payloadCallback =
    object : PayloadCallback() {
      override fun onPayloadReceived(endpointId: String, payload: Payload) {
        payload.asBytes()?.let {
          emit(ProximityEvent.DataReceived(peerId = endpointId, data = it))
        }
      }

      override fun onPayloadTransferUpdate(endpointId: String, update: PayloadTransferUpdate) {
        // No-op; consumers use end-to-end ack at the application layer.
      }
    }
}
