/**
 * Parity test — GroupCredentialContext JSON wire format.
 *
 * Asserts the discriminated-union Zod schema in
 * packages/shared/src/types/groupContext.ts accepts the JSON shape produced
 * by Swift's JSONEncoder for the `GroupCredentialContext` enum
 * (solidarity/Models/GroupCredentialContext.swift) and that re-encoding
 * yields the SAME canonical shape.
 *
 * Swift enum (associated value):
 *   enum GroupCredentialContext: Codable {
 *     case personal
 *     case group(GroupCredentialInfo)
 *   }
 *
 * Swift's default Codable synthesis for associated-value enums emits one of:
 *   { "personal": {} }
 *   { "group": { "_0": { ...GroupCredentialInfo } } }
 *
 * BUT the TS schema uses a TAGGED-UNION shape that matches the actual
 * production wire (see groupContext.ts):
 *   { "type": "personal" }
 *   { "type": "group", "info": { groupId, groupName, ... } }
 *
 * The Swift production wire goes through a custom encoder/decoder (see Swift
 * `Codable` extension below) so both ends speak the tagged-union form. Until
 * a generated golden fixture exists, this test pins the canonical sample
 * directly. When the Swift fixture exporter is extended:
 *   TODO(parity-fixtures): add
 *     packages/parity-fixtures/fixtures/groups/group_context_round_trip.json
 *     generated by solidarityTests/FixtureExporter.test_exportGroupContext.
 *
 * Run:
 *   cd apps/expo && bun test __tests__/parity/groupContext.parity.test.ts
 */
import { describe, expect, it } from 'bun:test';

import { groupCredentialContextSchema } from '@solidarity/shared';

// ─── Personal variant ───────────────────────────────────────────────────────

describe('GroupCredentialContext parity: personal variant', () => {
  it('parses the tagged-union "personal" shape', () => {
    const wire = JSON.parse('{"type":"personal"}') as unknown;
    const parsed = groupCredentialContextSchema.parse(wire);
    expect(parsed.type).toBe('personal');
  });

  it('round-trips through JSON without loss', () => {
    const original = { type: 'personal' as const };
    const parsed = groupCredentialContextSchema.parse(original);
    const re = JSON.parse(JSON.stringify(parsed)) as unknown;
    const re2 = groupCredentialContextSchema.parse(re);
    expect(re2).toEqual({ type: 'personal' });
  });

  it('rejects an unknown discriminator', () => {
    expect(() =>
      groupCredentialContextSchema.parse({ type: 'self-signed' })
    ).toThrow();
  });

  it('rejects a missing discriminator', () => {
    expect(() => groupCredentialContextSchema.parse({})).toThrow();
  });
});

// ─── Group variant ──────────────────────────────────────────────────────────

// Sample mirrors the Swift GroupCredentialInfo struct, field-for-field.
// Fields (from solidarity/Models/GroupCredentialContext.swift):
//   groupId: String           — UUID-string
//   groupName: String         — display name
//   merkleRoot: String        — hex string (snapshot at issuance)
//   issuedBy: String          — owner record id
//   issuedAt: Date            — Swift JSONEncoder default = seconds-since-1970,
//                                 but our parity tests use ISO-8601 (see
//                                 business_card_round_trip.json).
//   proofRequired: Bool
//
// TODO(parity-fixtures): Replace this inline sample with a JSON blob generated
// by solidarityTests/FixtureExporter.test_exportGroupContext once the Swift
// exporter is extended. Until then, the shape is taken verbatim from the
// Swift Codable spec.
const SAMPLE_GROUP_JSON = JSON.stringify({
  type: 'group',
  info: {
    groupId: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    groupName: 'Aurora',
    merkleRoot: 'deadbeefcafebabe0011223344556677',
    issuedBy: 'me',
    issuedAt: '2026-05-24T00:00:00Z',
    proofRequired: true,
  },
});

describe('GroupCredentialContext parity: group variant', () => {
  it('parses the tagged-union "group" shape into the GroupCredentialInfo struct', () => {
    const wire = JSON.parse(SAMPLE_GROUP_JSON) as unknown;
    const parsed = groupCredentialContextSchema.parse(wire);
    if (parsed.type !== 'group') throw new Error('expected group variant');
    expect(parsed.info.groupId).toBe('f47ac10b-58cc-4372-a567-0e02b2c3d479');
    expect(parsed.info.groupName).toBe('Aurora');
    expect(parsed.info.merkleRoot).toBe('deadbeefcafebabe0011223344556677');
    expect(parsed.info.issuedBy).toBe('me');
    expect(parsed.info.proofRequired).toBe(true);
    // Date round-trips through z.coerce.date — should be a real Date.
    expect(parsed.info.issuedAt).toBeInstanceOf(Date);
    expect(parsed.info.issuedAt.toISOString()).toBe('2026-05-24T00:00:00.000Z');
  });

  it('rejects non-hex merkleRoot (catches wire drift)', () => {
    expect(() =>
      groupCredentialContextSchema.parse({
        type: 'group',
        info: {
          groupId: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
          groupName: 'Aurora',
          merkleRoot: 'not-hex-zzz',
          issuedBy: 'me',
          issuedAt: '2026-05-24T00:00:00Z',
          proofRequired: true,
        },
      })
    ).toThrow();
  });

  it('rejects empty groupId / groupName (would orphan a credential)', () => {
    expect(() =>
      groupCredentialContextSchema.parse({
        type: 'group',
        info: {
          groupId: '',
          groupName: 'Aurora',
          merkleRoot: 'deadbeef',
          issuedBy: 'me',
          issuedAt: '2026-05-24T00:00:00Z',
          proofRequired: true,
        },
      })
    ).toThrow();
  });

  it('round-trips JSON.stringify → JSON.parse → schema without losing fields', () => {
    const wire = JSON.parse(SAMPLE_GROUP_JSON) as unknown;
    const parsed = groupCredentialContextSchema.parse(wire);
    // Round-trip through the wire: Date becomes ISO string, parse again.
    const re = JSON.parse(JSON.stringify(parsed)) as unknown;
    const re2 = groupCredentialContextSchema.parse(re);
    if (re2.type !== 'group') throw new Error('expected group variant');
    expect(re2.info.groupId).toBe('f47ac10b-58cc-4372-a567-0e02b2c3d479');
    expect(re2.info.proofRequired).toBe(true);
    expect(re2.info.issuedAt.toISOString()).toBe('2026-05-24T00:00:00.000Z');
  });
});

// ─── Discriminator boundary cases ───────────────────────────────────────────

describe('GroupCredentialContext parity: discriminator', () => {
  it('"group" variant without info is rejected', () => {
    expect(() =>
      groupCredentialContextSchema.parse({ type: 'group' })
    ).toThrow();
  });

  it('"personal" variant with an extra info field still parses (forward-compat)', () => {
    // Zod's strict mode is off by default for discriminatedUnion variants,
    // so extra fields are dropped silently. This mirrors Swift's behaviour
    // of ignoring unknown keys in associated-value Codable enums.
    const parsed = groupCredentialContextSchema.parse({
      type: 'personal',
      extraIgnored: { whatever: true },
    });
    expect(parsed.type).toBe('personal');
  });
});
